services:
  db:
    image: postgres:16
    container_name: canvas-execution-db
    environment:
      POSTGRES_DB: workflowdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - workflow_pg_data:/var/lib/postgresql/data

volumes:
  workflow_pg_data:
